<a href="https://colab.research.google.com/github/Aman2125/Numpy_CampusX_Practice/blob/main/3)aman_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#np.sort
Return a sorted copy of an array


In [2]:
#code
import numpy as np
a= np.random.randint(1,100,15)
a

array([65, 16, 51, 42, 13, 97, 97,  1, 97, 77,  7, 29, 92, 91,  3])

In [15]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[92, 88, 15, 55],
       [76, 65, 71, 96],
       [87, 29, 14, 35],
       [94, 92, 74, 86],
       [80, 75,  3,  4],
       [32, 86, 69, 52]])

In [7]:
np.sort(a) #default ascending sorting
np.sort(a)[::-1] #for descending order sorting

array([87, 60, 56, 51, 47, 41, 40, 36, 32, 28, 25, 14,  9,  7,  1])

In [6]:
np.sort(b) #for row wise sorting
np.sort(b ,axis=0) #for col wise sorting

array([[19, 11,  1, 10],
       [28, 43, 25, 16],
       [59, 50, 32, 25],
       [66, 55, 41, 62],
       [66, 60, 84, 75],
       [92, 88, 98, 98]])

#np.append
The numpy.append() appends values along the mentioned axis at the end of the array

In [8]:
#code
np.append(a,200) #200 appended in the end

array([ 41,   9,  40,  28,  25,  32,   1,  36,  47,   7,  51,  87,  14,
        56,  60, 200])

In [10]:
#in 2d
np.append(b,np.ones((b.shape[0],1)) , axis=1) #adding a column with 1 in the end of b
# np.append(b,np.random.random((b.shape[0] ,1)) , axis =1) adding random numbers

array([[59., 60., 84., 16.,  1.],
       [66., 11., 32., 62.,  1.],
       [92., 88., 41., 75.,  1.],
       [66., 43.,  1., 25.,  1.],
       [19., 50., 98., 10.,  1.],
       [28., 55., 25., 98.,  1.]])

#np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [12]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [13]:
np.concatenate((c,d),axis=0) #for row wise concatenation


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((c,d),axis=1) #for col wise concatenation

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

#np.unique
with the help of np.unique() method , we can get the unique values from an array given as parameter in np.unique() method.

In [15]:
e = np.array([1,1,1,2,2,3,3,4,4,5,5,5,6,6,6])
f = np.array([[1,2,3,2] , [1,2,2,3]])
print(e)
print(f)

[1 1 1 2 2 3 3 4 4 5 5 5 6 6 6]
[[1 2 3 2]
 [1 2 2 3]]


In [16]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

#np.expand_dims
with the help of Numpy.expand_dims() method , we can get the expanded dimension of the array.


In [19]:
a.shape

(15,)

In [20]:
np.expand_dims(a , axis = 0).shape #dimension expanded

(1, 15)

In [21]:
np.expand_dims(a,axis=1).shape

(15, 1)

#np.where
The numpy.where() function returns the indices of element in an input array where the given condition is satisfied.

In [22]:
a

array([41,  9, 40, 28, 25, 32,  1, 36, 47,  7, 51, 87, 14, 56, 60])

In [23]:
#find all the indices with the values greater than 50
np.where(a>50)

(array([10, 11, 13, 14]),)

In [24]:
#replace all values >50 with 0
np.where(a>50 , 0 , a) #syntax np.where(condition , value , array)

array([41,  9, 40, 28, 25, 32,  1, 36, 47,  7,  0,  0, 14,  0,  0])

#np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [25]:
a

array([41,  9, 40, 28, 25, 32,  1, 36, 47,  7, 51, 87, 14, 56, 60])

In [26]:
np.argmax(a)

np.int64(11)

In [27]:
b

array([[59, 60, 84, 16],
       [66, 11, 32, 62],
       [92, 88, 41, 75],
       [66, 43,  1, 25],
       [19, 50, 98, 10],
       [28, 55, 25, 98]])

In [28]:
np.argmax(b,axis=0) #col wise maximum indices

array([2, 2, 4, 5])

In [29]:
np.argmax(b , axis=1) # row wise

array([2, 0, 0, 0, 2, 3])

In [30]:
#np.argmin
np.argmin(a) # tells us the minimum element index

np.int64(6)

#np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [31]:
a

array([41,  9, 40, 28, 25, 32,  1, 36, 47,  7, 51, 87, 14, 56, 60])

In [32]:
np.cumsum(a)

array([ 41,  50,  90, 118, 143, 175, 176, 212, 259, 266, 317, 404, 418,
       474, 534])

In [16]:
b

array([[92, 88, 15, 55],
       [76, 65, 71, 96],
       [87, 29, 14, 35],
       [94, 92, 74, 86],
       [80, 75,  3,  4],
       [32, 86, 69, 52]])

In [34]:
np.cumsum(b , axis=0) #col wise cumulative sum

array([[ 59,  60,  84,  16],
       [125,  71, 116,  78],
       [217, 159, 157, 153],
       [283, 202, 158, 178],
       [302, 252, 256, 188],
       [330, 307, 281, 286]])

In [35]:
np.cumsum(b , axis=1)

array([[ 59, 119, 203, 219],
       [ 66,  77, 109, 171],
       [ 92, 180, 221, 296],
       [ 66, 109, 110, 135],
       [ 19,  69, 167, 177],
       [ 28,  83, 108, 206]])

In [36]:
#np.cumprod
np.cumprod(a) #finds cumaltive product


array([                  41,                  369,                14760,
                     413280,             10332000,            330624000,
                  330624000,          11902464000,         559415808000,
              3915910656000,      199711443456000,    17374895580672000,
         243248538129408000, -4824825938462703616,  5658348871590608896])

#np.percentile
numpy.percentile() function used to compute the nth percentile of the given data(array elemets) along the specified axis.

In [37]:
a

array([41,  9, 40, 28, 25, 32,  1, 36, 47,  7, 51, 87, 14, 56, 60])

In [38]:
#find 100 percentile ie maximum number
np.percentile(a,100)

np.float64(87.0)

In [3]:
np.percentile(a,50)

np.float64(51.0)

#np.histogram
Numpy has a built in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [5]:
a

array([65, 16, 51, 42, 13, 97, 97,  1, 97, 77,  7, 29, 92, 91,  3])

In [6]:
np.histogram(a,bins=[0,20,40,60,80,100])

(array([5, 1, 2, 2, 5]), array([  0,  20,  40,  60,  80, 100]))

#np.corrcoef
Return Pearson product-moment correlation coefficients.
Tells how much two quantity is correlated with each other.

In [7]:
salary = np.array([2000,3000,2300,45000,20000])
experience = np.array([1,2,3,2,4])

np.corrcoef(salary , experience)

array([[1.        , 0.13347905],
       [0.13347905, 1.        ]])

#np.isin
With the help of numpy.isin() method , we can see that one array having values are checked in a differet numpy array having different elements with different sizes.

Searching multiple items at once.

In [8]:
a

array([65, 16, 51, 42, 13, 97, 97,  1, 97, 77,  7, 29, 92, 91,  3])

In [10]:
items = [1,2,35,65,88,34,75,22,9,87,5,34,97]
np.isin(a,items)

array([ True, False, False, False, False,  True,  True,  True,  True,
       False, False, False, False, False, False])

#np.flip
The numpy.flip() function reverses the oreder of array elements along the specified axis , preserving the shape of the array.

In [11]:
a

array([65, 16, 51, 42, 13, 97, 97,  1, 97, 77,  7, 29, 92, 91,  3])

In [12]:
np.flip(a)

array([ 3, 91, 92, 29,  7, 77, 97,  1, 97, 97, 13, 42, 51, 16, 65])

In [17]:
b

array([[92, 88, 15, 55],
       [76, 65, 71, 96],
       [87, 29, 14, 35],
       [94, 92, 74, 86],
       [80, 75,  3,  4],
       [32, 86, 69, 52]])

In [19]:
np.flip(b , axis = 0) #for col flip

array([[32, 86, 69, 52],
       [80, 75,  3,  4],
       [94, 92, 74, 86],
       [87, 29, 14, 35],
       [76, 65, 71, 96],
       [92, 88, 15, 55]])

#np.put
The numpy.put() function replaces elements of an array with the given values of p_array. Array indexed works on flattened array.

In [20]:
a

array([65, 16, 51, 42, 13, 97, 97,  1, 97, 77,  7, 29, 92, 91,  3])

In [21]:
#change 1st and 2nd item
np.put(a,[0,1],[110,530]) #does the permanent changes
a

array([110, 530,  51,  42,  13,  97,  97,   1,  97,  77,   7,  29,  92,
        91,   3])

#np.delete
The numpy.delete() function returns a new array with the deletion of subarrays along with the mentioned axis.

In [22]:
a

array([110, 530,  51,  42,  13,  97,  97,   1,  97,  77,   7,  29,  92,
        91,   3])

In [23]:
np.delete(a,0) #provide indices to delete the element

array([530,  51,  42,  13,  97,  97,   1,  97,  77,   7,  29,  92,  91,
         3])

In [25]:
np.delete(a ,[2,4,5])

array([110, 530,  42,  97,   1,  97,  77,   7,  29,  92,  91,   3])

#Set Functions


*   np.union1d
*   np.intersect1d

*   np.setdiff1d
*   np.setxor1d

*   np.in1d






In [26]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m , n)

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
np.intersect1d(m,n)

array([3, 4, 5])

In [28]:
np.setdiff1d(m,n)

array([1, 2])

In [29]:
np.setxor1d(m,n) #common removed

array([1, 2, 6, 7])

In [31]:
np.in1d(m,1)

/tmp/ipython-input-3930963099.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])